"""Public API for the standalone complex-task resolver package."""

from .contracts import (
    COMPLEX_TASK_FOLLOWUP_TASK_VERSION,
    COMPLEX_TASK_GRAPH_VERSION,
    COMPLEX_TASK_NODE_ATTEMPT_VERSION,
    COMPLEX_TASK_NODE_VERSION,
    COMPLEX_TASK_RESOLUTION_PACKET_VERSION,
    COMPLEX_TASK_RESOLVER_CONTEXT_VERSION,
    COMPLEX_TASK_RESOLVER_OPTIONS_VERSION,
    COMPLEX_TASK_RESOLVER_REQUEST_VERSION,
    COMPLEX_TASK_SUBAGENT_REQUEST_VERSION,
    COMPLEX_TASK_SUBAGENT_RESULT_VERSION,
    ComplexTaskValidationError,
    project_complex_task_packet,
    validate_complex_task_graph,
    validate_complex_task_followup_task,
    validate_complex_task_node,
    validate_complex_task_node_attempt,
    validate_complex_task_resolution_packet,
    validate_complex_task_resolver_context,
    validate_complex_task_resolver_options,
    validate_complex_task_resolver_request,
    validate_complex_task_subagent_request,
    validate_complex_task_subagent_result,
)
from .constants import (
    DEFAULT_OPTION_LIMITS,
    DEFAULT_SUBAGENT_MAX_ATTEMPTS,
    OPTION_LIMIT_CAPS,
)
from .service import resolve_complex_task

__all__ = [
    "COMPLEX_TASK_FOLLOWUP_TASK_VERSION",
    "COMPLEX_TASK_GRAPH_VERSION",
    "COMPLEX_TASK_NODE_ATTEMPT_VERSION",
    "COMPLEX_TASK_NODE_VERSION",
    "COMPLEX_TASK_RESOLUTION_PACKET_VERSION",
    "COMPLEX_TASK_RESOLVER_CONTEXT_VERSION",
    "COMPLEX_TASK_RESOLVER_OPTIONS_VERSION",
    "COMPLEX_TASK_RESOLVER_REQUEST_VERSION",
    "COMPLEX_TASK_SUBAGENT_REQUEST_VERSION",
    "COMPLEX_TASK_SUBAGENT_RESULT_VERSION",
    "ComplexTaskValidationError",
    "DEFAULT_OPTION_LIMITS",
    "DEFAULT_SUBAGENT_MAX_ATTEMPTS",
    "OPTION_LIMIT_CAPS",
    "project_complex_task_packet",
    "validate_complex_task_graph",
    "validate_complex_task_followup_task",
    "validate_complex_task_node",
    "validate_complex_task_node_attempt",
    "validate_complex_task_resolution_packet",
    "validate_complex_task_resolver_context",
    "validate_complex_task_resolver_options",
    "validate_complex_task_resolver_request",
    "validate_complex_task_subagent_request",
    "validate_complex_task_subagent_result",
    "resolve_complex_task",
]
