"""Central constants for the standalone complex-task resolver."""

DEFAULT_OPTION_LIMITS = {
    "max_iterations": 4,
    "max_nodes": 8,
    "max_depth": 3,
    "max_node_attempts": 3,
    "max_subagent_attempts": 1,
}
OPTION_LIMIT_CAPS = dict(DEFAULT_OPTION_LIMITS)
DEFAULT_SUBAGENT_MAX_ATTEMPTS = DEFAULT_OPTION_LIMITS["max_subagent_attempts"]
MAX_RAG_CALLS_PER_RUN = 2

REVIEW_CASE_ID_PREFIX = "ctr"
REVIEW_CASE_ID_DIGIT_COUNT = 3

FOLLOWUP_TASKS_PER_SOURCE_LIMIT = 2
FAILED_PACKET_GRAPH_LIMIT = 1
ROOT_NODE_COUNT = 1
ROOT_DEPTH = 0
ROOT_CHILD_DEPTH = 1
MIXED_PREREQUISITE_EXTRA_NODE_COUNT = 2
MIXED_PREREQUISITE_REQUIRED_DEPTH = 2
SYNTHESIS_TASK_INDEX_START = 2
RECENT_NODE_ATTEMPT_LIMIT = 3
SAFE_FAILURE_TEXT_LIMIT = 300
TRACE_TEXT_LIMIT = 4000
TRACE_LIST_LIMIT = 12
TRACE_DICT_LIMIT = 24
TEXT_ELLIPSIS = "..."

STAGE_LLM_TEMPERATURE = 0.1
STAGE_LLM_TOP_P = 0.7

NO_ATTEMPTS_RECORDED = 0
DEPENDENCY_FAILURE_ATTEMPTS = 1
EXECUTED_CALCULATION_ATTEMPTS = 1
