"""Session-scoped RAG Cache 2 runtime.

This module intentionally does not import or reuse the legacy ``rag.cache``
implementation. Cache 2 is an in-memory, process-local LRU intended for helper
agent retrieval results and initializer strategy hints.
"""

from __future__ import annotations

import hashlib
import json
import logging
import os
from collections import OrderedDict
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any

from kazusa_ai_chatbot.rag.cache2_events import (
    CacheDependency,
    CacheInvalidationEvent,
)

logger = logging.getLogger(__name__)

DEFAULT_CACHE2_MAX_ENTRIES = int(os.getenv("RAG_CACHE2_MAX_ENTRIES", "5000"))


def stable_cache_key(namespace: str, payload: dict[str, Any]) -> str:
    """Build a stable exact-match cache key.

    Args:
        namespace: Logical cache namespace, usually the agent or policy name.
        payload: JSON-serializable key material.

    Returns:
        A SHA-256 hex digest over the namespace and canonical JSON payload.
    """
    raw = json.dumps(
        {"namespace": namespace, "payload": payload},
        ensure_ascii=False,
        sort_keys=True,
        default=str,
    )
    return hashlib.sha256(raw.encode("utf-8")).hexdigest()


def _now_utc() -> datetime:
    """Return the current UTC timestamp."""
    return datetime.now(timezone.utc)


def _field_matches(entry_value: str, event_value: str) -> bool:
    """Return whether one dependency field is compatible with an event field."""
    return not entry_value or not event_value or entry_value == event_value


def _timestamp_overlaps_dependency(
    dependency: CacheDependency,
    event: CacheInvalidationEvent,
) -> bool:
    """Return whether an event timestamp overlaps a dependency time range.

    Args:
        dependency: Dependency recorded on the cache entry.
        event: Write event being applied to the cache.

    Returns:
        True when the event has no timestamp, the dependency has no closed
        range, or the event timestamp falls inside the dependency range.
    """
    if not event.timestamp:
        return True
    if dependency.from_timestamp and event.timestamp < dependency.from_timestamp:
        return False
    if dependency.to_timestamp and event.timestamp > dependency.to_timestamp:
        return False
    return True


def dependency_matches_event(
    dependency: CacheDependency,
    event: CacheInvalidationEvent,
) -> bool:
    """Return whether an invalidation event affects a dependency.

    Args:
        dependency: Data scope recorded on a cache entry.
        event: Data-write event emitted by a writer.

    Returns:
        True when the source matches, all populated scope fields are compatible,
        and the event timestamp overlaps the dependency's historical range.
    """
    if dependency.source != event.source:
        return False

    scoped_fields_match = (
        _field_matches(dependency.platform, event.platform)
        and _field_matches(dependency.platform_channel_id, event.platform_channel_id)
        and _field_matches(dependency.global_user_id, event.global_user_id)
        and _field_matches(dependency.display_name, event.display_name)
    )
    if not scoped_fields_match:
        return False

    return _timestamp_overlaps_dependency(dependency, event)


@dataclass
class Cache2Entry:
    """Single in-memory Cache 2 entry.

    Args:
        cache_key: Stable exact key generated by the cache policy.
        cache_name: Logical cache namespace.
        result: Cached result payload.
        dependencies: Data scopes that can invalidate this entry.
        metadata: Optional trace metadata for debugging.
        created_at: Entry creation timestamp.
        last_hit_at: Most recent cache-hit timestamp.
        hit_count: Number of times this entry has been served.
    """

    cache_key: str
    cache_name: str
    result: dict[str, Any]
    dependencies: list[CacheDependency]
    metadata: dict[str, Any] = field(default_factory=dict)
    created_at: datetime = field(default_factory=_now_utc)
    last_hit_at: datetime | None = None
    hit_count: int = 0


class RAGCache2Runtime:
    """Process-local LRU cache for Cache 2 entries."""

    def __init__(self, *, max_entries: int = DEFAULT_CACHE2_MAX_ENTRIES) -> None:
        """Initialize the in-memory runtime.

        Args:
            max_entries: Maximum number of entries retained before LRU eviction.
        """
        self._max_entries = max_entries
        self._entries: OrderedDict[str, Cache2Entry] = OrderedDict()
        self._hits = 0
        self._misses = 0
        self._invalidations = 0
        self._evictions = 0

    async def get(self, cache_key: str) -> dict[str, Any] | None:
        """Retrieve a cached result by exact key.

        Args:
            cache_key: Stable exact key generated by a cache policy.

        Returns:
            The cached result payload, or ``None`` on miss.
        """
        entry = self._entries.get(cache_key)
        if entry is None:
            self._misses += 1
            return None

        entry.hit_count += 1
        entry.last_hit_at = _now_utc()
        self._entries.move_to_end(cache_key)
        self._hits += 1
        return dict(entry.result)

    async def store(
        self,
        *,
        cache_key: str,
        cache_name: str,
        result: dict[str, Any],
        dependencies: list[CacheDependency],
        metadata: dict[str, Any] | None = None,
    ) -> None:
        """Store or replace a cache entry.

        Args:
            cache_key: Stable exact key generated by a cache policy.
            cache_name: Logical cache namespace.
            result: JSON-like payload to serve on future hits.
            dependencies: Data scopes that can invalidate this entry.
            metadata: Optional trace metadata.
        """
        self._entries[cache_key] = Cache2Entry(
            cache_key=cache_key,
            cache_name=cache_name,
            result=dict(result),
            dependencies=list(dependencies),
            metadata=dict(metadata or {}),
        )
        self._entries.move_to_end(cache_key)
        self._evict_if_needed()

    async def invalidate(self, event: CacheInvalidationEvent) -> int:
        """Invalidate entries affected by a write event.

        Args:
            event: Domain event emitted by a writer such as conversation save or
                consolidator persistence.

        Returns:
            Number of entries removed.
        """
        keys_to_remove: list[str] = []
        for cache_key, entry in self._entries.items():
            if any(dependency_matches_event(dep, event) for dep in entry.dependencies):
                keys_to_remove.append(cache_key)

        for cache_key in keys_to_remove:
            self._entries.pop(cache_key, None)

        self._invalidations += len(keys_to_remove)
        if keys_to_remove:
            logger.debug(
                "RAG Cache 2 invalidated %d entries for source=%s reason=%s",
                len(keys_to_remove),
                event.source,
                event.reason,
            )
        return len(keys_to_remove)

    async def clear(self) -> int:
        """Clear every session cache entry.

        Returns:
            Number of entries removed.
        """
        removed = len(self._entries)
        self._entries.clear()
        self._invalidations += removed
        return removed

    def get_stats(self) -> dict[str, Any]:
        """Return runtime cache counters.

        Returns:
            Dict with size, hit/miss, invalidation, and eviction counters.
        """
        total = self._hits + self._misses
        return {
            "size": len(self._entries),
            "max_entries": self._max_entries,
            "hits": self._hits,
            "misses": self._misses,
            "hit_rate": self._hits / total if total else 0.0,
            "invalidations": self._invalidations,
            "evictions": self._evictions,
        }

    def _evict_if_needed(self) -> None:
        """Evict least-recently-used entries until the cache is within budget."""
        while len(self._entries) > self._max_entries:
            self._entries.popitem(last=False)
            self._evictions += 1


_runtime: RAGCache2Runtime | None = None


def get_rag_cache2_runtime() -> RAGCache2Runtime:
    """Return the process-local Cache 2 runtime singleton.

    Returns:
        The in-memory Cache 2 runtime for this Python process.
    """
    global _runtime
    if _runtime is None:
        _runtime = RAGCache2Runtime()
    return _runtime
