"""Session-scoped RAG Cache 2 runtime.

This module owns the in-memory, process-local LRU for helper agent retrieval
results and initializer strategy hints.
"""

from __future__ import annotations

import hashlib
import json
import logging
from collections import OrderedDict
from copy import deepcopy
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any

from kazusa_ai_chatbot.config import RAG_CACHE2_MAX_ENTRIES
from kazusa_ai_chatbot.rag.cache2_events import (
    CacheDependency,
    CacheInvalidationEvent,
)

logger = logging.getLogger(__name__)

DEFAULT_CACHE2_MAX_ENTRIES = RAG_CACHE2_MAX_ENTRIES


def stable_cache_key(namespace: str, payload: dict[str, Any]) -> str:
    """Build a stable exact-match cache key.

    Args:
        namespace: Logical cache namespace, usually the agent or policy name.
        payload: JSON-serializable key material.

    Returns:
        A SHA-256 hex digest over the namespace and canonical JSON payload.
    """
    raw = json.dumps(
        {"namespace": namespace, "payload": payload},
        ensure_ascii=False,
        sort_keys=True,
        default=str,
    )
    return hashlib.sha256(raw.encode("utf-8")).hexdigest()


def _now_utc() -> datetime:
    """Return the current UTC timestamp."""
    return datetime.now(timezone.utc)


def _field_matches(entry_value: str, event_value: str) -> bool:
    """Return whether one dependency field is compatible with an event field."""
    return not entry_value or not event_value or entry_value == event_value


def _timestamp_overlaps_dependency(
    dependency: CacheDependency,
    event: CacheInvalidationEvent,
) -> bool:
    """Return whether an event timestamp overlaps a dependency time range.

    Args:
        dependency: Dependency recorded on the cache entry.
        event: Write event being applied to the cache.

    Returns:
        True when the event has no timestamp, the dependency has no closed
        range, or the event timestamp falls inside the dependency range.
    """
    if not event.timestamp:
        return True
    if dependency.from_timestamp and event.timestamp < dependency.from_timestamp:
        return False
    if dependency.to_timestamp and event.timestamp > dependency.to_timestamp:
        return False
    return True


def dependency_matches_event(
    dependency: CacheDependency,
    event: CacheInvalidationEvent,
) -> bool:
    """Return whether an invalidation event affects a dependency.

    Args:
        dependency: Data scope recorded on a cache entry.
        event: Data-write event emitted by a writer.

    Returns:
        True when the source matches, all populated scope fields are compatible,
        and the event timestamp overlaps the dependency's historical range.
    """
    if dependency.source != event.source:
        return False

    scoped_fields_match = (
        _field_matches(dependency.platform, event.platform)
        and _field_matches(dependency.platform_channel_id, event.platform_channel_id)
        and _field_matches(dependency.global_user_id, event.global_user_id)
        and _field_matches(dependency.display_name, event.display_name)
    )
    if not scoped_fields_match:
        return False

    return _timestamp_overlaps_dependency(dependency, event)


@dataclass
class Cache2Entry:
    """Single in-memory Cache 2 entry.

    Args:
        cache_key: Stable exact key generated by the cache policy.
        cache_name: Logical cache namespace.
        result: Cached result payload.
        dependencies: Data scopes that can invalidate this entry.
        metadata: Optional trace metadata for debugging.
        created_at: Entry creation timestamp.
        last_hit_at: Most recent cache-hit timestamp.
        hit_count: Number of times this entry has been served.
    """

    cache_key: str
    cache_name: str
    result: Any
    dependencies: list[CacheDependency]
    metadata: dict[str, Any] = field(default_factory=dict)
    created_at: datetime = field(default_factory=_now_utc)
    last_hit_at: datetime | None = None
    hit_count: int = 0


@dataclass
class AgentCacheStats:
    """Lookup counters for one Cache 2 agent.

    Args:
        agent_name: Stable display name for the agent or cache stage.
        hit_count: Number of cache hits attributed to the agent.
        miss_count: Number of cache misses attributed to the agent.
    """

    agent_name: str
    hit_count: int = 0
    miss_count: int = 0

    def as_dict(self) -> dict[str, Any]:
        """Return the public health payload for this agent.

        Returns:
            Dict containing only sanitized scalar stats.
        """
        total = self.hit_count + self.miss_count
        return {
            "agent_name": self.agent_name,
            "hit_count": self.hit_count,
            "miss_count": self.miss_count,
            "hit_rate": self.hit_count / total if total else 0.0,
        }


class RAGCache2Runtime:
    """Process-local LRU cache for Cache 2 entries."""

    def __init__(self, *, max_entries: int = DEFAULT_CACHE2_MAX_ENTRIES) -> None:
        """Initialize the in-memory runtime.

        Args:
            max_entries: Maximum number of entries retained before LRU eviction.
        """
        self._max_entries = max_entries
        self._entries: OrderedDict[str, Cache2Entry] = OrderedDict()
        self._hits = 0
        self._misses = 0
        self._invalidations = 0
        self._evictions = 0
        self._agent_stats: dict[str, AgentCacheStats] = {}

    async def get(
        self,
        cache_key: str,
        *,
        cache_name: str = "",
        agent_name: str = "",
    ) -> Any | None:
        """Retrieve a cached result by exact key.

        Args:
            cache_key: Stable exact key generated by a cache policy.
            cache_name: Logical cache namespace used to attribute misses when
                no cache entry exists yet.
            agent_name: Stable agent display name used for health stats.

        Returns:
            The cached result payload, or ``None`` on miss.
        """
        entry = self._entries.get(cache_key)
        if entry is None:
            self._misses += 1
            self._record_agent_lookup(
                agent_name=self._resolve_agent_name(
                    agent_name=agent_name,
                    cache_name=cache_name,
                    entry=None,
                ),
                hit=False,
            )
            return None

        entry.hit_count += 1
        entry.last_hit_at = _now_utc()
        self._entries.move_to_end(cache_key)
        self._hits += 1
        self._record_agent_lookup(
            agent_name=self._resolve_agent_name(
                agent_name=agent_name,
                cache_name=cache_name,
                entry=entry,
            ),
            hit=True,
        )
        return deepcopy(entry.result)

    async def store(
        self,
        *,
        cache_key: str,
        cache_name: str,
        result: Any,
        dependencies: list[CacheDependency],
        metadata: dict[str, Any] | None = None,
    ) -> None:
        """Store or replace a cache entry.

        Args:
            cache_key: Stable exact key generated by a cache policy.
            cache_name: Logical cache namespace.
            result: JSON-like payload to serve on future hits.
            dependencies: Data scopes that can invalidate this entry.
            metadata: Optional trace metadata.
        """
        self._entries[cache_key] = Cache2Entry(
            cache_key=cache_key,
            cache_name=cache_name,
            result=deepcopy(result),
            dependencies=list(dependencies),
            metadata=dict(metadata or {}),
        )
        self._entries.move_to_end(cache_key)
        self._evict_if_needed()

    async def invalidate(self, event: CacheInvalidationEvent) -> int:
        """Invalidate entries affected by a write event.

        Args:
            event: Domain event emitted by a writer such as conversation save or
                consolidator persistence.

        Returns:
            Number of entries removed.
        """
        keys_to_remove: list[str] = []
        for cache_key, entry in self._entries.items():
            if any(dependency_matches_event(dep, event) for dep in entry.dependencies):
                keys_to_remove.append(cache_key)

        for cache_key in keys_to_remove:
            self._entries.pop(cache_key, None)

        self._invalidations += len(keys_to_remove)
        if keys_to_remove:
            logger.debug(
                "RAG Cache 2 invalidated %d entries for source=%s reason=%s",
                len(keys_to_remove),
                event.source,
                event.reason,
            )
        return len(keys_to_remove)

    async def clear(self) -> int:
        """Clear every session cache entry.

        Returns:
            Number of entries removed.
        """
        removed = len(self._entries)
        self._entries.clear()
        self._invalidations += removed
        return removed

    def get_stats(self) -> dict[str, Any]:
        """Return runtime cache counters.

        Returns:
            Dict with size, hit/miss, invalidation, and eviction counters.
        """
        total = self._hits + self._misses
        return {
            "size": len(self._entries),
            "max_entries": self._max_entries,
            "hits": self._hits,
            "misses": self._misses,
            "hit_rate": self._hits / total if total else 0.0,
            "invalidations": self._invalidations,
            "evictions": self._evictions,
        }

    def get_agent_stats(self) -> list[dict[str, Any]]:
        """Return sanitized per-agent Cache 2 lookup counters.

        Returns:
            List of dicts containing ``agent_name``, ``hit_count``,
            ``miss_count``, and ``hit_rate`` only.
        """
        return [
            stats.as_dict()
            for stats in sorted(
                self._agent_stats.values(),
                key=lambda item: item.agent_name,
            )
        ]

    def _record_agent_lookup(self, *, agent_name: str, hit: bool) -> None:
        """Increment the per-agent lookup counter when attribution exists.

        Args:
            agent_name: Stable display name for the lookup owner.
            hit: Whether the lookup was a cache hit.
        """
        if not agent_name:
            return

        stats = self._agent_stats.get(agent_name)
        if stats is None:
            stats = AgentCacheStats(agent_name=agent_name)
            self._agent_stats[agent_name] = stats

        if hit:
            stats.hit_count += 1
        else:
            stats.miss_count += 1

    def _resolve_agent_name(
        self,
        *,
        agent_name: str,
        cache_name: str,
        entry: Cache2Entry | None,
    ) -> str:
        """Resolve a public agent name for lookup stats.

        Args:
            agent_name: Explicit caller-supplied display name.
            cache_name: Cache namespace supplied by the caller.
            entry: Cache entry on hit, or ``None`` on miss.

        Returns:
            Agent display name, or an empty string when the lookup cannot be
            safely attributed.
        """
        explicit_agent_name = str(agent_name or "").strip()
        if explicit_agent_name:
            return explicit_agent_name

        if entry is not None:
            metadata_agent = str(entry.metadata.get("agent_name", "")).strip()
            if metadata_agent:
                return metadata_agent
            cache_name = cache_name or entry.cache_name

        normalized_cache_name = str(cache_name or "").strip()
        if normalized_cache_name.startswith("rag2_"):
            return normalized_cache_name[len("rag2_"):]
        return normalized_cache_name

    def _evict_if_needed(self) -> None:
        """Evict least-recently-used entries until the cache is within budget."""
        while len(self._entries) > self._max_entries:
            self._entries.popitem(last=False)
            self._evictions += 1


_runtime: RAGCache2Runtime | None = None


def get_rag_cache2_runtime() -> RAGCache2Runtime:
    """Return the process-local Cache 2 runtime singleton.

    Returns:
        The in-memory Cache 2 runtime for this Python process.
    """
    global _runtime
    if _runtime is None:
        _runtime = RAGCache2Runtime()
    return _runtime
