"""Central constants for the routed WebAgent3 helper."""

GENERATOR_TEMPERATURE = 0.3
GENERATOR_TOP_P = 0.9
DETERMINISTIC_STAGE_TEMPERATURE = 0.0
DETERMINISTIC_STAGE_TOP_P = 1.0
RECENT_OBSERVATION_LIMIT = 3
SUCCESS_SCORE_THRESHOLD = 80
PARTIAL_SCORE_THRESHOLD = 50
RUN_CONTRACT_MAX_ATTEMPTS = 3

STATUS_RANK_NOT_FOUND = 0
STATUS_RANK_PARTIAL = 1
STATUS_RANK_SUCCESS = 2

MAX_SEARCH_ATTEMPTS = 4
SEARCH_QUERY_CHAR_LIMIT = 180
SEARCH_PURPOSE_CHAR_LIMIT = 220
ATTEMPT_EVIDENCE_CHAR_LIMIT = 1800
EXPANDED_SEARCH_OUTPUT_CHAR_LIMIT = 12000
COMPOSITE_QUERY_WORD_THRESHOLD = 10
COMPOSITE_QUERY_SIGNAL_THRESHOLD = 3
COMPOSITE_QUERY_LONG_SIGNAL_THRESHOLD = 2
COMPARISON_QUERY_SIGNAL_THRESHOLD = 2
SEARCH_ATTEMPT_TEMPERATURE = 0.1
SEARCH_ATTEMPT_TOP_P = 0.8
