"""Public entrypoint for the code-writing subagent."""

from kazusa_ai_chatbot.coding_agent.code_writing.agent import run
from kazusa_ai_chatbot.coding_agent.code_writing.models import (
    CodeWritingRequest,
    CodeWritingResult,
    ModulePMInput,
    ModuleContractEvaluation,
    ModuleProgrammerContract,
    ModuleProgrammerResult,
    ModuleProgrammerSymbol,
    PatchArtifact,
    PatchOperation,
    PatchValidationSummary,
    SourceOwnerCandidate,
    WritingFileDemand,
    WritingFileModuleContract,
    WritingFilePlanEvaluation,
    WritingFileResolution,
    WritingPMDecision,
    WritingPMInput,
    WritingPatcherInput,
    WritingPatcherReport,
    WritingProgrammerReport,
)

__all__ = [
    "CodeWritingRequest",
    "CodeWritingResult",
    "ModulePMInput",
    "ModuleContractEvaluation",
    "ModuleProgrammerContract",
    "ModuleProgrammerResult",
    "ModuleProgrammerSymbol",
    "PatchArtifact",
    "PatchOperation",
    "PatchValidationSummary",
    "SourceOwnerCandidate",
    "WritingFileDemand",
    "WritingFileModuleContract",
    "WritingFilePlanEvaluation",
    "WritingFileResolution",
    "WritingPMDecision",
    "WritingPMInput",
    "WritingPatcherInput",
    "WritingPatcherReport",
    "WritingProgrammerReport",
    "run",
]
