import json
import logging
from typing import Annotated, TypedDict
import datetime

from langchain_core.messages import AIMessage, HumanMessage, SystemMessage, ToolMessage
from langchain_core.tools import tool
from langchain_openai import ChatOpenAI
from langgraph.graph import END, START, StateGraph
from langgraph.graph.message import add_messages

from kazusa_ai_chatbot.config import LLM_API_KEY, LLM_BASE_URL, LLM_MODEL, MAX_WEB_SEARCH_AGENT_RETRY
from kazusa_ai_chatbot.mcp_client import mcp_manager
from kazusa_ai_chatbot.utils import parse_llm_json_output, get_llm

logger = logging.getLogger(__name__)


@tool
async def web_search(
    query: str,
    pageno: int = 1,
    time_range: str = "",
    language: str = ""
) -> str:
    """Performs a web search using the SearXNG API.
    
    Args:
        query: The search query string (required)
        pageno: Search page number starting from 1 (default: 1)
        time_range: Time filter for search results - use 'day', 'month', 'year' or leave empty for all time (default: "")
        language: Language code for results (e.g., 'en', 'zh', 'fr') or leave empty for default (default: "")
    """
    return await mcp_manager.call_tool("mcp-searxng__searxng_web_search", {
        "query": query,
        "pageno": pageno,
        "time_range": time_range,
        "language": language,
        "safesearch": 0  # none
    })


@tool
async def web_url_read(
    url: str,
    startChar: int = 0,
    maxLength: int = 1000,
    section: str = "",
    paragraphRange: str = "",
    readHeadings: bool = False
) -> str:
    """Reads and extracts content from a specific URL.
    
    Args:
        url: The complete URL to read content from (required)
        startChar: Starting character position for content extraction (default: 0)
        maxLength: Maximum number of characters to return, 0 for no limit (default: 1000)
        section: Extract content under a specific heading text (default: "")
        paragraphRange: Return specific paragraph ranges like '1-5', '3', or '10-' (default: "")
        readHeadings: If True, returns only the list of headings instead of full content (default: False)
    """
    args = {
        "url": url,
        "startChar": startChar,
        "section": section,
        "paragraphRange": paragraphRange,
        "readHeadings": readHeadings
    }
    if maxLength > 0:
        args["maxLength"] = maxLength
    
    return await mcp_manager.call_tool("mcp-searxng__web_url_read", args)


_ALL_TOOLS = [web_search, web_url_read]
_TOOLS_BY_NAME = {tool.name: tool for tool in _ALL_TOOLS}



class WebSearchState(TypedDict):
    task: str
    context: dict
    next_tool: str
    expected_response: str
    messages: Annotated[list, add_messages]
    should_stop: bool
    retry: int
    timestamp: str

    # Source information
    knowledge_metadata: dict
    
    # Final output
    final_response: str
    final_status: str
    final_reason: str


async def web_search_tool_call_executor(state: WebSearchState) -> dict:
    """Execute the tool calls generated by the LLM"""
    results = []
    last_message = state["messages"][-1]

    # Safety: Check if the LLM actually requested tools
    if hasattr(last_message, "tool_calls") and last_message.tool_calls:
        for tool_call in last_message.tool_calls:
            try:
                tool = _TOOLS_BY_NAME[tool_call["name"]]
                observation = await tool.ainvoke(tool_call["args"])
            except KeyError:
                observation = {"error": f"Incorrect tool was invoked: {tool_call['name']}"}
                logger.error(f"Incorrect tool was invoked: {tool_call['name']}")
            except Exception as e:
                observation = {"error": str(e)}
                logger.error(f"Error executing tool {tool_call['name']}: {e}")
                
            results.append(ToolMessage(
                content=json.dumps(observation, ensure_ascii=False), 
                tool_call_id=tool_call["id"]
            ))
    
    return {"messages": results}


_WEB_SEARCH_GENERATOR_PROMPT = """\
你是一个专家级的网络搜索代理 (Web Search Agent)。你的目标是通过互联网检索最准确、最及时的信息来完成任务。

# 核心准则
- **行为分解**：搜索 (`web_search`) 只是为了寻找线索；阅读 (`web_url_read`) 才是为了获取知识。严禁仅根据搜索结果摘要（Snippets）撰写最终回答。
- **拒绝假设**：严禁猜测未知的 URL 或事实。如果信息不存在，请如实反馈。
- **反馈至上**：评估员 (Evaluator) 的反馈是你的最高指令。如果评估员要求你“深入阅读”，不要再次发起搜索。

# 搜索策略 (Advanced Query Engineering)
1. **多维度搜索**：如果第一次搜索无果，尝试使用近义词、英文翻译（针对技术或国际话题）或特定的日期限定。
2. **搜索语法**：合理利用高级语法，如 `"精确匹配"`，`site:official-website.com`，或 `-排除无关词`。
3. **优先级排序**：优先选择权威来源（政府、大型机构、官方文档）而非博客或社交媒体。

# 任务流程
1. **历史审计**：核查 `messages`。如果上一步已经得到了搜索列表，这一步通常应该使用 `web_url_read` 读取其中最相关的 1-3 个链接。
2. **识别缺口**：对比 `task` 与当前已获取的“正文内容”。
3. **执行行动**：
   - 需要新线索？执行 `web_search`。
   - 已有线索但无详情？执行 `web_url_read`。
   - 无法继续？在回复中说明原因。

# 语言与时间
- **当前时间参考**：{timestamp}。
- **语言匹配**：默认使用任务语言搜索。但对于全球性技术、科学或国际新闻，建议同时尝试英文搜索。

# 输入格式
{{
    "task": "任务描述",
    "context": 辅助搜索信息,
    "messages": [包含评估员反馈的历史记录]
}}
"""
_web_search_tool_call_generator_llm = get_llm(temperature=0.5, top_p=0.9).bind_tools(_ALL_TOOLS)
async def web_search_tool_call_generator(state: WebSearchState) -> dict:    
    agent_tools = "\n".join([f"- {tool.name}: {tool.description}" for tool in _ALL_TOOLS])
    system_prompt = SystemMessage(content=_WEB_SEARCH_GENERATOR_PROMPT.format(agent_tools=agent_tools, timestamp=state["timestamp"]))

    user_input = {
        "task": state["task"],
        "context": state["context"],
    }
    human_message = HumanMessage(content=json.dumps(user_input, ensure_ascii=False))

    # Trim the amount of history into the generator
    if len(state["messages"]) > 3:
        relevant_history = [state["messages"][0]] + state["messages"][-3:]
    else:
        relevant_history = state["messages"]

    response = await _web_search_tool_call_generator_llm.ainvoke([system_prompt, human_message] + relevant_history)

    return {"messages": [response]}


_WEB_SEARCH_EVALUATOR_PROMPT = """\
你是一个高级检索评估专家。你的任务是分析检索到的内容与用户任务之间的差距，并决定后续行动。

# 核心任务
1. **决定状态**：
   - 如果检索内容已完全覆盖任务需求，或者已经达到“足够好 (Satisficing)”的程度，设置 `should_stop: true`。
   - 如果关键信息缺失、过时或仅有摘要而无详情，设置 `should_stop: false`。
2. **提供建议**：如果未通过，必须给出具体的“执行指令”：
   - **优化方向**：如果结果太杂，建议增加“双引号”精确匹配或 `site:` 限制。
   - **工具切换**：如果已有相关链接但只有 Snippets，强制建议使用 `web_url_read` 读取正文，禁止重复搜索。
   - **拼写纠错**：观察搜索结果中是否有“您是不是要找...”，如果是，建议修正关键词。

# 停止原则 (Critical)
符合以下任一条件时，必须设置 `should_stop: true`：
1. **足够好原则**：检索内容已覆盖 80% 以上的核心需求，足以构成一个准确、有用的回答，无需为追求 100% 的边缘细节继续浪费 Token。
2. **边际收益递减**：历史记录显示已尝试了 3 种以上不同的搜索策略且结果雷同，没有新信息出现。
3. **确认无果**：已穷尽相关关键词和域名限制（如 search, site: official_site 等）依然无法找到目标信息。

# 消息时效与计算
- **当前时间**：{timestamp}
- **时间敏感度**：如果任务涉及“最新”、“最近”、“三天内”或特定年份，必须核对结果日期。
- **动态计算**：如果用户要求“过去一周”，请根据当前时间计算出具体的日期范围，并在 `feedback` 中告知 Generator 使用该范围。

# 工具使用约束
- 你只能根据以下工具集给出建议，禁止建议使用不存在的工具：
{agent_tools}
- **警告**：评估专家仅负责逻辑判断，禁止在 response 中生成任何实际的 tool_call。

# 输入格式
{{
    "task": "任务描述",
    "expected_response": "用户期待的回复内容和格式，有可能包含更多搜索细节",
    "call_history": [已执行的工具、参数及结果摘要],
    "retry": 当前重试次数 n / MAX_RETRY
}}

# 输出格式
请务必返回合法的 JSON 字符串，包含以下字段：
{{
    "feedback": "给 Generator 的下一步具体动作建议。如果 should_stop 为 true，此处可留空或总结检索结论。",
    "should_stop": true 或 false
}}
"""
_web_search_tool_call_evaluator_llm = get_llm(temperature=0.0, top_p=1.0)
async def web_search_tool_call_evaluator(state: WebSearchState) -> dict:
    retry = state.get("retry", 0) + 1

    call_history = []
    for i, msg in enumerate(state["messages"]):
        if isinstance(msg, AIMessage) and getattr(msg, "tool_calls", None):
            for tc in msg.tool_calls:
                result_content = "No result found"
                for next_msg in state["messages"][i+1:]:
                    if isinstance(next_msg, ToolMessage) and next_msg.tool_call_id == tc["id"]:
                        result_content = next_msg.content
                        break
                
                call_history.append({
                    "tool": tc["name"],
                    "arguments": tc["args"],
                    "result": result_content
                })

    agent_tools = "\n".join([f"- {tool.name}: {tool.description}" for tool in _ALL_TOOLS])
    system_prompt = SystemMessage(content=_WEB_SEARCH_EVALUATOR_PROMPT.format(
        agent_tools=agent_tools,
        timestamp=state["timestamp"]
    ))

    evaluation_input = {
        "task": state["task"],
        "expected_response": state["expected_response"],
        "call_history": call_history,
        "retry": f"{retry}/{MAX_WEB_SEARCH_AGENT_RETRY}",
    }
    evaluation_message = HumanMessage(content=json.dumps(evaluation_input, ensure_ascii=False))

    response = await _web_search_tool_call_evaluator_llm.ainvoke([system_prompt, evaluation_message])
    result = parse_llm_json_output(response.content)
    
    should_stop = result.get("should_stop", False)
    feedback = result.get("feedback", "")

    # If the evaluator actively decides to stop then the information is enough. We shall record the sources.
    knowledge_metadata = {}
    if should_stop:
        last_tool_call = call_history[-1]
        if last_tool_call:
            # Make sure the result is actually generated by tool. otherwise we don't care
            knowledge_metadata["tool"] = last_tool_call['tool']
            knowledge_metadata["result"] = last_tool_call['result']

    if retry >= MAX_WEB_SEARCH_AGENT_RETRY:
        should_stop = True

    final_message = HumanMessage(
        content=f"Evaluator Feedback:\n{feedback}",
        name="evaluator"
    )

    return {
        "messages": [final_message],
        "should_stop": should_stop,
        "retry": retry,
        "knowledge_metadata": knowledge_metadata,
    }



_WEB_SEARCH_FINALIZER_PROMPT = """\
你是一个信息整理专家。你的任务是将检索到的信息整理成用户友好的格式。

# 核心任务
1. **整理信息**：将检索到的关键信息根据**任务描述**整理成**用户期待的格式**。
2. **评估信息**：根据评估者最终反馈评估检索到的信息是否满足任务描述的要求。

# 输出说明
- response: 根据 expected_response 整理后的信息，严禁输出非字符串内容
- score: 评估分数，范围 0-100，表示检索到的信息满足任务描述的程度
- reason: 评估原因（一句话之内概括）

# 输入格式
{
    "task": "任务描述",
    "content": "收集到的数据",
    "evaluator_feedback": "评估者最终反馈",
    "expected_response": "用户期望的输出内容和格式"
}

# 输出格式
请务必返回合法的 JSON 字符串，包含以下字段：
{
    "response": "string",
    "score": <int: 0-100>,
    "reason": "string"
}
"""
_web_search_tool_call_finalizer_llm = get_llm(temperature=0.0, top_p=1.0)
async def web_search_tool_call_finalizer(state: WebSearchState) -> dict:
    tool_messages = [m.content for m in state["messages"] if isinstance(m, ToolMessage)]
    tool_results = "\n".join(tool_messages) if tool_messages else "No information retrieved."

    evaluator_feedback = [
        m.content for m in state["messages"] 
        if isinstance(m, HumanMessage) and m.name == "evaluator"
    ]
    evaluator_feedback = evaluator_feedback[-1] if evaluator_feedback else ""

    system_prompt = SystemMessage(content=_WEB_SEARCH_FINALIZER_PROMPT)

    finalizer_input = {
        "task": state["task"],
        "expected_response": state["expected_response"],
        "content": tool_results,
        "evaluator_feedback": evaluator_feedback,
    }
    human_message = HumanMessage(content=json.dumps(finalizer_input, ensure_ascii=False))

    response = await _web_search_tool_call_finalizer_llm.ainvoke([system_prompt, human_message])
    result = parse_llm_json_output(response.content)

    status = ""
    score = result.get("score", 0)
    if score > 80:
        status = "success"
    elif score > 50:
        status = "partial"
    else:
        status = "not_found"

    if "response" not in result:
        result["response"] = "No information retrieved."
        result["score"] = 0
        status = "error"
        logger.error(f"No response provided by finalizer, raw result: \n{result}")

    if "reason" not in result:
        result["reason"] = "No reason provided."
    
    return {
        "final_response": result.get("response"), 
        "final_status": status, 
        "final_reason": result.get("reason")
    }


async def web_search_agent(
    task: str,
    context: dict,
    expected_response: str,
    timestamp: str | None = None
) -> dict:

    if timestamp is None:
        # Fallback to UTC time
        timestamp = datetime.datetime.now(datetime.timezone.utc).isoformat()

    sub_agent_builder = StateGraph(WebSearchState)
        
    sub_agent_builder.add_node("web_search_tool_call_executor", web_search_tool_call_executor)
    sub_agent_builder.add_node("web_search_tool_call_generator", web_search_tool_call_generator)
    sub_agent_builder.add_node("web_search_tool_call_evaluator", web_search_tool_call_evaluator)
    sub_agent_builder.add_node("web_search_tool_call_finalizer", web_search_tool_call_finalizer)

    sub_agent_builder.add_edge(START, "web_search_tool_call_generator")

    sub_agent_builder.add_edge("web_search_tool_call_generator", "web_search_tool_call_executor")
    sub_agent_builder.add_edge("web_search_tool_call_executor", "web_search_tool_call_evaluator")

    sub_agent_builder.add_conditional_edges(
        "web_search_tool_call_evaluator",
        lambda s: "loop" if not s.get("should_stop", False) else "finalize",
        {
            "loop": "web_search_tool_call_generator",
            "finalize": "web_search_tool_call_finalizer",
        },
    )
    sub_agent_builder.add_edge("web_search_tool_call_finalizer", END)

    sub_graph = sub_agent_builder.compile()

    subState: WebSearchState = {
        "task": task,
        "context": context,
        "next_tool": "",
        "expected_response": expected_response,
        "messages": [],
        "should_stop": False,
        "retry": 0,
        "final_status": "error",
        "final_reason": "",
        "final_response": "",
        "timestamp": timestamp,
    }

    result = await sub_graph.ainvoke(subState)

    return {
        "status": result.get("final_status"),
        "reason": result.get("final_reason"),
        "response": result.get("final_response"),
        "knowledge_metadata": result.get("knowledge_metadata", {}),
    }


async def test_main():
    # Connect to MCP tool servers
    try:
        await mcp_manager.start()
    except Exception:
        logger.exception("MCP manager failed to start — tools will be unavailable")

    result = await web_search_agent(
        task="杏山千纱的信息",
        context={},
        expected_response="相关来源链接"
    )

    print(result["status"])
    print(result["reason"])
    print(result["response"])
    print(result["knowledge_metadata"])
    await mcp_manager.stop()


if __name__ == "__main__":
    import asyncio
    asyncio.run(test_main())